# Site Settings
title: Dhurba Baral
email: dhurba87@gmail.com
description: Some text about your blog.
baseurl: "https://blog.dhurbabaral.com.np" # the subpath of your site, e.g. /blog
url: "https://blog.dhurbabaral.com.np" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Jekflix
user_description: Some text about you.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: dhurba87
facebook_username: dhurba87
twitter_username: dhurba87
instagram_username: dhurba087
linkedin_username: dhurba87
medium_username: dhurba87

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
